File structure
FACG6/Gaza-Freelancing-Community pull request #42
Opened 2019-03-19 13:18 UTC by Fatmasiam

Relates : #9

2019-03-19 13:21 UTC, kannanhassouna requested changes

2019-03-19 13:21 UTC, knanahassouna1 commented on package.json
> +    "dotenv": "^7.0.0",
unnecessary modules

2019-03-19 18:39 UTC, kannanhassouna requested changes
in ``` public/js/helper/dom.js ``` the name of the file should descriptive that file will help in what

2019-03-19 18:40 UTC, knanahassouna1 commented
thank you for editing ``` file structure ``` issue

2019-03-19 18:47 UTC, knanahassouna1 commented
You should include package-lock.json file in your P.R

2019-03-19 18:57 UTC, kannanhassouna requested changes
Add ``` .env ``` to .gitignore file

2019-03-19 20:16 UTC, Fatmasiam commented
> Add `.env` to .gitignore file

done

2019-03-19 20:19 UTC, Fatmasiam commented on package.json
> +    "dotenv": "^7.0.0",
I remove it

2019-03-19 20:20 UTC, Fatmasiam commented
> You should include package-lock.json file in your P.R

but that's just file structure .

2019-03-20 05:16 UTC, kannanhassouna approved these changes

2019-03-20 07:26 UTC, Angham116 approved these changes

2019-03-20 07:54 UTC, Anies12 approved these changes

2019-03-20 07:55 UTC, ahmedalmi95 approved these changes

2019-03-20 07:55 UTC, merged