Deploying travis
FACG6/Gaza-Freelancing-Community pull request #50
Opened 2019-03-20 08:43 UTC by Anies12

removed a space before "script" , travis was unable to parse the .yml file

2019-03-20 09:40 UTC, kannanhassouna requested changes
you have a problem with Travis  , please review #52

2019-03-20 09:40 UTC, knanahassouna1 commented on .travis.yml
>    - PGPORT=5432
white space

2019-03-21 07:16 UTC, Fatmasiam approved these changes

2019-03-21 12:46 UTC, Angham116 approved these changes

2019-03-21 13:07 UTC, ahmedalmi95 approved these changes

2019-03-21 13:16 UTC, kannanhassouna requested changes

2019-03-21 13:16 UTC, knanahassouna1 commented on test/test.js
> +})
insert white space

2019-03-21 13:16 UTC, knanahassouna1 commented on test/test.js
> +test('asd',(t)=> {
use Eslint

2019-03-21 13:16 UTC, knanahassouna1 commented on package.json
> +    "nodemon": "^1.18.10",
remove  ``` nodemon ``` 
your pull request about travis and testing why you add ``` nodemon ```

2019-03-21 18:24 UTC, Fatmasiam requested changes
there is conflict try to solve it

2019-03-22 13:25 UTC, closed without merging