Test query add user
FACG6/Gaza-Freelancing-Community pull request #66
Opened 2019-03-20 14:18 UTC by AhmedAl-Almi

test for add user query for first name and last name and mobile number.

2019-03-21 07:26 UTC, Fatmasiam approved these changes

2019-03-21 12:55 UTC, Angham116 approved these changes

2019-03-21 13:52 UTC, tomduggan85 commented on src/database/queries/addData.js
> +  const queryObj = {
@AhmedAl-Almi Looks good!  You could use `hashPass` to hash the password right in this function, once #72 is merged.  I see that `hashPass` returns a promise so this function then will have to change slightly, to wait for the promise.  This looks great for now!

2019-03-21 18:52 UTC, Fatmasiam requested changes
CONFLICT !!!!

2019-03-23 19:45 UTC, knanahassouna1 commented
Closed Pull Request,
### DON'T MERGE THIS PULL REQUEST

2019-03-23 19:45 UTC, closed without merging