Read me
FACG6/Gaza-Freelancing-Community pull request #67
Opened 2019-03-20 18:05 UTC by Angham116

wrote the initial readMe file.

2019-03-20 21:17 UTC, ahmedalmi95 approved these changes
in the next time don't forget to add all your team as viewers

2019-03-21 07:15 UTC, Fatmasiam approved these changes

2019-03-23 19:01 UTC, kannanhassouna requested changes

2019-03-23 19:01 UTC, knanahassouna1 commented on README.md
> +### **Our Solutione** :
typo

2019-03-23 19:07 UTC, kannanhassouna approved these changes

2019-03-23 19:08 UTC, merged