Check email query
FACG6/Gaza-Freelancing-Community pull request #68
Opened 2019-03-21 07:54 UTC by Angham116

#21 made ```checkEmail``` query with a test for all expected results.

2019-03-21 12:29 UTC, ahmedalmi95 approved these changes
white space

2019-03-21 12:37 UTC, Fatmasiam commented on src/database/config/db_build.sql
> +COMMIT
add new line

2019-03-21 13:35 UTC, tomduggan85 commented on src/database/config/db_build.sql
> +VALUES ('a', 'b', 'a.gmail.com', 'https://github.com/angham', 'https://www.iconspng.com/image/36709/face-avatar-man-male-handsome-3', '0097234567', '1234');
@Angham116 You could use the hashed and salted version of 1234 as your password value that you store in the database here, which would let you type 1234 into the login field and successfully log in with this account.

2019-03-21 13:36 UTC, tomduggan85 commented on test/test.js
> +});
@Angham116 Nice job adding tests!

2019-03-21 13:44 UTC, Angham116 commented on test/test.js
> +});
thanks

2019-03-22 20:41 UTC, Anies12 approved these changes

2019-03-23 20:27 UTC, kannanhassouna approved these changes

2019-03-23 20:27 UTC, kannanhassouna commented on package.json
> +    "nodemon": "^1.18.10",
``` nodemon ``` ?

2019-03-23 20:27 UTC, kannanhassouna commented on src/database/config/db_build.sql
> +COMMIT;
``` commit ``` twice  ?

2019-03-23 20:27 UTC, knanahassouna1 commented on test/test.js
> +tape('Test checkEmail query function if there is no email match with income email', (t) => {
you can make your tests cleaner 

```javascript
 tape('Test checkEmail query function if there is email match with income email', (t) => {
  reBuildDB()
    .then(() => checkEmail('a@gmail.com'))
    .then((result) => {
      t.equal(result.rows[0], undefined, 'should not there any values in rows');
      t.end();
    })
    .catch(error =>  {
       t.error(error)
       t.end();
     });
});
```

2019-03-23 20:40 UTC, kannanhassouna requested changes

2019-03-23 20:40 UTC, knanahassouna1 commented on test/test.js
> +      t.equal(result.rows[0].email, 'a.gmail.com', 'the first row should be not empty');
```suggestion
      t.equal(result.rows[0].email, undefined, 'the first row should be not empty');
```

2019-03-23 23:46 UTC, Fatmasiam commented on src/database/config/db_build.sql
> +COMMIT;
@knanahassouna1  just one ?!

2019-03-23 23:46 UTC, Fatmasiam commented on test/test.js
> +tape('Test checkEmail query function if there is no email match with income email', (t) => {
@Angham116  as the last test !!!

2019-03-24 13:34 UTC, closed without merging