New sigup dom
FACG6/Gaza-Freelancing-Community pull request #71
Opened 2019-03-21 09:43 UTC by Anies12

2019-03-21 12:23 UTC, ahmedalmi95 requested changes
white space

2019-03-21 12:34 UTC, Fatmasiam commented on .gitignore
> +.env
add new line

2019-03-21 12:34 UTC, Fatmasiam commented on public/js/signup.js
> +});
and here add new line

2019-03-21 12:34 UTC, Fatmasiam commented on src/views/signup.hbs
> +</div>
and here

2019-03-21 13:39 UTC, tomduggan85 commented
@Anies12 Hey 👋I added some comments to the other signup dom PR (#69) that apply here too.  I see now that #69 is closed and this one is probably the one you'll merge.

2019-03-23 08:55 UTC, Fatmasiam commented on public/js/signup.js
> +                            swal(text: `${res.error}`, type: "warning");
how you give the swal key and value without object brackets ??!!

2019-03-23 08:55 UTC, Fatmasiam commented on public/js/signup.js
> +                        swal(text: 'Error, please try again..', type: "warning");
and here ?

2019-03-24 14:34 UTC, closed without merging